// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhL5mT10X5Abxe2fF2yUOeTpSh0O_C8gs',
    appId: '1:121691340828:web:095f80881cf2cde73d1fd9',
    messagingSenderId: '121691340828',
    projectId: 'ecuafilms-f9775',
    authDomain: 'ecuafilms-f9775.firebaseapp.com',
    storageBucket: 'ecuafilms-f9775.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU0HZykRFTxWAU_iTIgpQVoJgoKDXshkQ',
    appId: '1:121691340828:android:9f0af93b064fff323d1fd9',
    messagingSenderId: '121691340828',
    projectId: 'ecuafilms-f9775',
    storageBucket: 'ecuafilms-f9775.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNe1p9xVNRToC9KZavbVZjOxevNd6-y4U',
    appId: '1:121691340828:ios:c487c03a0c28dec23d1fd9',
    messagingSenderId: '121691340828',
    projectId: 'ecuafilms-f9775',
    storageBucket: 'ecuafilms-f9775.appspot.com',
    iosClientId: '121691340828-q0alu4q75cuqe3pc0t0hb8egf4bhu25l.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecuafilms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNe1p9xVNRToC9KZavbVZjOxevNd6-y4U',
    appId: '1:121691340828:ios:c487c03a0c28dec23d1fd9',
    messagingSenderId: '121691340828',
    projectId: 'ecuafilms-f9775',
    storageBucket: 'ecuafilms-f9775.appspot.com',
    iosClientId: '121691340828-q0alu4q75cuqe3pc0t0hb8egf4bhu25l.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecuafilms',
  );
}
