name: ecuafilms
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.5
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.6
  cloud_firestore: ^4.3.1
  http: ^0.13.5
  carousel_slider: ^4.2.1
  flutter_fadein: ^2.0.0
  flutter_native_splash: ^2.2.17
  another_flushbar: ^1.12.29

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#242A32"
  image: "assets/img/logo.png"

flutter:

 
  uses-material-design: true

 
  assets:
   - assets/img/
  
  #fonts:
  # - family: Roboto
     #fonts:
  #    - asset: assets/fonts/Roboto-Black.ttf
   #   - asset: assets/fonts/Roboto-BlackItalic.ttf
    #  - asset: assets/fonts/Roboto-Bold.ttf
     # - asset: assets/fonts/Roboto-BoldItalic.ttf
      #- asset: assets/fonts/Roboto-Light.ttf
       
  #         style: italic
   #- family: Poppins
    # fonts:
     #   - asset: assets/fonts/Poppins-Black.ttf
      #  - asset: assets/fonts/Poppins-Italic.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
 